/************************************************************************/
/*  api_tool_generator.cpp                                              */
/************************************************************************/
/*  This file is part of:                                               */
/*                                GodotJS-Ext                           */
/*              https://github.com/Daylily-Zeleen/GodotJS-Ext           */
/*                                                                      */
/*  Copyright (c) 2026-present 忘忧の (Daylily-Zeleen)                  */
/*                 - Contact: daylily-zeleen@foxmail.com                */
/*                                                                      */
/*  This library is free software; you can redistribute it and/or       */
/*  modify it under the terms of the GNU Lesser General Public          */
/*  License as published by the Free Software Foundation; either        */
/*  version 2.1 of the License, or (at your option) any later version.  */
/*                                                                      */
/*  This library is distributed in the hope that it will be useful,     */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of      */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU   */
/*  Lesser General Public License for more details.                     */
/*                                                                      */
/*  You should have received a copy of the GNU Lesser General Public    */
/*  License along with this library; if not,                            */
/*  see <https://www.gnu.org/licenses/>.                                */
/************************************************************************/

#include "weaver-editor/jsb_editor_progress.h"

// editor/api_tool_generator.cpp
// Subprocess generation implementation (TOOLS_ENABLED only).
// Detects project path, Godot executable, launches subprocess.
// Handles backup/restore of existing extension_api.json.

#include "api_tool_generator.h"
#include "api_tool_parser.h"
#include <godot_cpp/classes/dir_access.hpp>
#include <godot_cpp/classes/engine.hpp>
#include <godot_cpp/classes/file_access.hpp>
#include <godot_cpp/classes/json.hpp>
#include <godot_cpp/classes/os.hpp>
#include <godot_cpp/classes/project_settings.hpp>
#include <godot_cpp/variant/utility_functions.hpp>

using namespace godot;

namespace api_tool::internal {

// ============================================================================
// Generate API JSON via subprocess
// ============================================================================

Error ApiGenerator::generate_api_json(const String &p_project_dir, String &r_api_file_path) {
	// Detect the Godot executable path
	String godot_exe = OS::get_singleton()->get_executable_path();
	ERR_FAIL_COND_V_MSG(godot_exe.is_empty(), ERR_FILE_NOT_FOUND, "[API Tool] Failed to detect Godot executable path");

	// Determine output path for extension_api.json
	r_api_file_path = p_project_dir + String("extension_api.json");

	// Backup existing extension_api.json before overwriting
	if (FileAccess::file_exists(r_api_file_path)) {
		String backup_path = r_api_file_path + String(".bak");
		Error err = DirAccess::rename_absolute(r_api_file_path, backup_path);
		ERR_FAIL_COND_V_MSG(err, err, "[API Tool] " + UtilityFunctions::error_string(err) + ": Failed to backup file: " + r_api_file_path);
	}

	// Launch Godot subprocess to dump extension API with docs
	PackedStringArray args;
	args.push_back("--headless");
	args.push_back("--path");
	args.push_back(p_project_dir);
	args.push_back("--dump-extension-api-with-docs");

	UtilityFunctions::print("[API Tool] Launching Godot subprocess to generate extension_api.json...");
	int pid = OS::get_singleton()->create_process(godot_exe, args);

	if (pid < 0) {
		ERR_FAIL_V_MSG(ERR_CANT_FORK, "[API Tool] " + UtilityFunctions::error_string(ERR_CANT_FORK) + ": Failed to launch Godot subprocess");
	}

	// Wait for subprocess to finish // 考虑改为异步等待
	while (OS::get_singleton()->is_process_running(pid)) {
		OS::get_singleton()->delay_usec(100000); // 100ms
	}

	// Check if the file was generated
	if (!FileAccess::file_exists(r_api_file_path)) {
		UtilityFunctions::push_error("[API Tool] extension_api.json was not generated by subprocess");
		ERR_FAIL_V_MSG(FAILED, "[API Tool] " + UtilityFunctions::error_string(FAILED) + ": [API Tool] extension_api.json was not generated by subprocess");
	}

	UtilityFunctions::print("[API Tool] extension_api.json generated successfully");
	return OK;
}

// ============================================================================
// Full pipeline: generate JSON -> parse -> write binary files
// ============================================================================

Error ApiGenerator::generate(const String &p_extension_api_json_path, const String &p_output_dir) {
	String out_dir = p_output_dir;
	ERR_FAIL_COND_V_MSG(out_dir.is_empty(), ERR_INVALID_PARAMETER, vformat("[API Tool] Failed to generate extension_api.json: %s", UtilityFunctions::error_string(ERR_INVALID_PARAMETER)));

	String json_text = FileAccess::get_file_as_string(p_extension_api_json_path);
	Error err = FileAccess::get_open_error();
	ERR_FAIL_COND_V_MSG(err, err, "[API Tool] " + UtilityFunctions::error_string(ERR_FILE_CANT_READ) + ": Failed to open extension_api.json");

	Variant result = JSON::parse_string(json_text);
	ERR_FAIL_COND_V_MSG(err, err, "[API Tool] " + UtilityFunctions::error_string(ERR_PARSE_ERROR) + ": Can't parse " + "extension_api.json");

	Dictionary root = result;

	// 3. Parse JSON -> binary files
	err = ApiParser::generate(root, out_dir);
	ERR_FAIL_COND_V_MSG(err, err, "[API Tool] " + UtilityFunctions::error_string(err) + ": Generate api file failed.");

	UtilityFunctions::print("[API Tool] Full generation pipeline completed successfully");
	return OK;
}

} //namespace api_tool::internal
