// uid://dxeepjb1uqdr7 This line is generated, don't modify or remove it.
import { Node } from "godot";

/**
 * Source map integration test fixture.
 *
 * This file is compiled by tsc (`sourceMap: true`, outDir `.godot/godotjs_ext`) into
 * `.godot/godotjs_ext/tests/中文路径/source-map-test.js` together with a real `.js.map`,
 * so the whole pipeline is exercised with a non-ascii directory.
 *
 * The stacktrace under test is the raw `error.stack` (generated by the JS engine from
 * the script name passed to `compile_function`) — the only thing TS can observe. The
 * checks verify:
 *  1. the generated filename keeps the full non-ascii directory and the `.js` extension
 *     (regression for the utf-8 byte-length bug in `impl::Helper::compile_function`;
 *     the C++ doctest only covers a hardcoded name, this checks the real tsc output path);
 *  2. the frame is in the `at ... (file.js:line:col)` form that `SourceMapCache::match()`
 *     consumes, so the C++ rewrite pipeline actually picks the frame up.
 *
 * The *rewritten* stacktrace itself is produced in C++ (`process_source_position`) and
 * cannot be read back from TS; that logic is covered by the C++ doctest
 * `[jsb.sourcemap] process_source_position rewrites stacktrace`.
 */
export default class SourceMapTest extends Node {
    _ready() {
        const error = new Error("SOURCE_MAP_TEST_MARKER");
        const rawStack = error.stack ?? error.message;

        const checks = [
            {
                name: "generated filename kept in full ('source-map-test.js')",
                pass: rawStack.includes("source-map-test.js"),
            },
            {
                name: "non-ascii directory preserved ('中文路径')",
                pass: rawStack.includes("中文路径"),
            },
            {
                name: "frame in `at ... (file.js:line:col)` form",
                pass: /at .+source-map-test\.js:\d+:\d+\)/.test(rawStack),
            },
        ];
        const allPassed = checks.every((check) => check.pass);

        // report the expected format, the stacktrace under test, and the check results
        console.log("=== [source-map-test] raw stacktrace check ===");
        console.log("expected: a V8 frame like `at fn (..../source-map-test.js:LINE:COL)` whose path keeps");
        console.log("          `中文路径` and the `.js` extension (utf-8 byte-length regression).");
        console.log("stacktrace under test (from `new Error().stack`):");
        console.log(rawStack);
        console.log("check results:");
        for (const check of checks) {
            console.log(`  [${check.pass ? "PASS" : "FAIL"}] ${check.name}`);
        }
        console.log(`result: ${allPassed ? "PASS - all checks passed" : "FAIL - see failing checks above"}`);

        // real assertions: a failed console.assert throws and fails the integration run
        console.assert(
            allPassed,
            `raw stacktrace checks failed:\n${checks.map((check) => `  [${check.pass ? "PASS" : "FAIL"}] ${check.name}`).join("\n")}\nstacktrace under test:\n${rawStack}`
        );
    }
}
