#  misc_changesets.yml
#
#  This file is part of:
#                                GodotJS-Ext
#              https://github.com/Daylily-Zeleen/GodotJS-Ext
#
#  Copyright (c) 2026-present 忘忧の (Daylily-Zeleen)
#                 - Contact: daylily-zeleen@foxmail.com
#  Copyright (c) Contributors of GodotJS
#                 - <https://github.com/godotjs/GodotJS>
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not,
#  see <https://www.gnu.org/licenses/>.

name: Changesets
on:
  workflow_call:
    outputs:
      publish:
        description: "Should publish"
        value: ${{ jobs.changesets.outputs.publish || 'false' }}

permissions:
  contents: write
  pull-requests: write

jobs:
  changesets:
    name: Changesets
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.should_publish.outputs.publish }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-install

      - name: Install dependencies
        run: pnpm install
        working-directory: scripts

      - name: Create and publish versions
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          version: pnpm ci:version
          cwd: scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Should publish
        id: should_publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HAS_CHANGESETS: ${{ steps.changesets.outputs.hasChangesets }}
        run: |
          SHOULD_PUBLISH=$(pnpm run ci:should-publish | tail -n 1)
          if [[ $SHOULD_PUBLISH == "true" && $HAS_CHANGESETS == "false" ]]; then
            echo "publish=true" >> $GITHUB_OUTPUT
          else
            echo "publish=false" >> $GITHUB_OUTPUT
          fi
        working-directory: scripts
